### ISSUE TITLE
Filtering by Geo Point

### ISSUE THREAD

**Issue by OlegoO** [VirtoCommerce/vc-module-catalog#88]
As a catalog client, I want to find geo-points within the specified distance of a central point.

### Acceptance criteria
- [ ] GIVEN Products with GeoPoints properties
WHEN I select property and central point
THEN I want to find products within the specified distance of a central point.

### Definition of Done
- [ ] Unit tests pass with Code coverage 100%
- [ ] Code review
- [ ] Documentation

### Tasks
- [ ] Support Geo Point by Elastic search
- [ ] Support Geo Point by Azure Search

**Comment by tatarincev** [comment]
Released https://github.com/VirtoCommerce/vc-module-catalog/releases/tag/v2.21.0
