### ISSUE TITLE
Sorting by Geo Point

### ISSUE THREAD

**Issue by OlegoO** [VirtoCommerce/vc-module-catalog#89]
As a catalog client, I want to sort products by distance from geo-point

### Acceptance criteria
- [ ] GIVEN Products with GeoPoints properties
WHEN I select property and central point
THEN I want to sort products by distance from central point.

### Definition of Done
- [ ] Unit tests pass with Code coverage 100%
- [ ] Code review
- [ ] Documentation

### Tasks
- [ ] Support Geo Point by Elastic search
- [ ] Support Geo Point by Azure Search

**Comment by tatarincev** [comment]
Released https://github.com/VirtoCommerce/vc-module-catalog/releases/tag/v2.21.0
